services:
  minio:
    image: minio/minio:latest
    container_name: MinIO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${MINIO_PORT}/minio/health/live"]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_CONSOLE_PORT}:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - app-net

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "${NATS_PORT}:4222"
      - "${NATS_MONITOR_PORT}:8222"
    command: [
      "-js",
      "-m", "${NATS_MONITOR_PORT}",
      "--store_dir", "/data"
    ]
    volumes:
      - nats_data:/data
    networks:
      - app-net

  app:
    build: .
    container_name: image-compressor-app
    ports:
      - "${HTTP_PORT}:8080"
    depends_on:
      minio:
        condition: service_healthy
      nats:
        condition: service_started
    environment:
      HTTP_PORT: ${HTTP_PORT}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY_ID}
      MINIO_SECRET_ACCESS_KEY: ${MINIO_SECRET_ACCESS_KEY}
      MINIO_SSL_MODE: ${MINIO_SSL_MODE}
      NATS_URL: ${NATS_DOCKER_URL}
    networks:
      - app-net

volumes:
  minio_data:
  nats_data:

networks:
  app-net:
